### ISSUE TITLE
WCGA-AA Color contrast ratio on "screen reader only" element

### ISSUE THREAD

**Issue by sandrina-p** [ctomczyk/aslint#2]
On [my website](http://sandrina-p.net) I have several elements with the class `.sr-only` that is used to hide visually the element and shows it only for screen readers.

The issue is aslint says it needs contrast.

```
Expected color contrast ratio at least 4.5:1, but got ratio: 4.26:1, background-color: #rgb(242, 242, 242), color: #rgb(0, 128, 128), level: AA, size: small.
Node: <h2 class="sr-only">Chat Bot sections</h2>
XPath: XPath string 
/html/body/main/div/nav/h2  
Impact: major
```

That happens because if I remove `sr-only` you can see the element has a teal color.

This is the CSS for `.sr-only`
```css
.sr-only {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0,0,0,0);
    border: 0;
}
```

I think your tool could be able to detect `.sr-only` elements and ignore them.
